config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :recipe_ingredients
  resources :messages
  resources :user_events
  resources :sources
  resources :events
  resources :locations
  resources :menu_recipes
  resources :recipes
  resources :menus
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/constituent.rb
class Constituent < ApplicationRecord
  belongs_to :source
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :location, optional: true
  belongs_to :menu, optional: true
  has_many :participants
  has_many :users, through: :participants
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :constituent
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :events
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :events
end

app/models/menu_recipe.rb
class MenuRecipe < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user_event
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :event

  enum participant_type: [:host, :guest]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :location
end

app/models/user.rb
class User < ApplicationRecord
  has_many :participants
  has_many :events, through: :participants

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:rsvp, :user_event_id, :is_paid)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menu_recipes_helper.rb
module MenuRecipesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rsvp %>
    <%= form.check_box :rsvp, id: :message_rsvp %>
  </div>

  <div class="field">
    <%= form.label :user_event_id %>
    <%= form.text_field :user_event_id, id: :message_user_event_id %>
  </div>

  <div class="field">
    <%= form.label :is_paid %>
    <%= form.check_box :is_paid, id: :message_is_paid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Rsvp</th>
      <th>User event</th>
      <th>Is paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.rsvp %></td>
        <td><%= message.user_event %></td>
        <td><%= message.is_paid %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rsvp:</strong>
  <%= @message.rsvp %>
</p>

<p>
  <strong>User event:</strong>
  <%= @message.user_event %>
</p>

<p>
  <strong>Is paid:</strong>
  <%= @message.is_paid %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>