config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :recipe_ingredients
  resources :messages
  resources :user_events
  resources :sources
  resources :events
  resources :locations
  resources :menu_recipes
  resources :recipes
  resources :menus
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/constituent.rb
class Constituent < ApplicationRecord
  belongs_to :source
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :location, optional: true
  belongs_to :menu, optional: true
  has_many :participants
  has_many :users, through: :participants
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :constituent
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :events
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :events
end

app/models/menu_recipe.rb
class MenuRecipe < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user_event
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :event

  enum participant_type: [:host, :guest]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :location
end

app/models/user.rb
class User < ApplicationRecord
  has_many :participants
  has_many :events, through: :participants

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:ingredient_name, :source_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menu_recipes_helper.rb
module MenuRecipesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/views/ingredients/_form.html.erb
<%= form_with(model: ingredient, local: true) do |form| %>
  <% if ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ingredient_name %>
    <%= form.text_field :ingredient_name, id: :ingredient_ingredient_name %>
  </div>

  <div class="field">
    <%= form.label :source_id %>
    <%= form.text_field :source_id, id: :ingredient_source_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Ingredient name</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.ingredient_name %></td>
        <td><%= ingredient.source %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ingredient name:</strong>
  <%= @ingredient.ingredient_name %>
</p>

<p>
  <strong>Source:</strong>
  <%= @ingredient.source %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>