config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :recipe_ingredients
  resources :messages
  resources :user_events
  resources :sources
  resources :events
  resources :locations
  resources :menu_recipes
  resources :recipes
  resources :menus
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/constituent.rb
class Constituent < ApplicationRecord
  belongs_to :source
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :location, optional: true
  belongs_to :menu, optional: true
  has_many :participants
  has_many :users, through: :participants
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :constituent
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :events
end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :events
end

app/models/menu_recipe.rb
class MenuRecipe < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user_event
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :event

  enum participant_type: [:host, :guest]
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/source.rb
class Source < ApplicationRecord
  belongs_to :location
end

app/models/user.rb
class User < ApplicationRecord
  has_many :participants
  has_many :events, through: :participants

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/user_events_controller.rb
class UserEventsController < ApplicationController
  before_action :set_user_event, only: [:show, :edit, :update, :destroy]

  # GET /user_events
  # GET /user_events.json
  def index
    @user_events = UserEvent.all
  end

  # GET /user_events/1
  # GET /user_events/1.json
  def show
  end

  # GET /user_events/new
  def new
    @user_event = UserEvent.new
  end

  # GET /user_events/1/edit
  def edit
  end

  # POST /user_events
  # POST /user_events.json
  def create
    @user_event = UserEvent.new(user_event_params)

    respond_to do |format|
      if @user_event.save
        format.html { redirect_to @user_event, notice: 'User event was successfully created.' }
        format.json { render :show, status: :created, location: @user_event }
      else
        format.html { render :new }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_events/1
  # PATCH/PUT /user_events/1.json
  def update
    respond_to do |format|
      if @user_event.update(user_event_params)
        format.html { redirect_to @user_event, notice: 'User event was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_event }
      else
        format.html { render :edit }
        format.json { render json: @user_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_events/1
  # DELETE /user_events/1.json
  def destroy
    @user_event.destroy
    respond_to do |format|
      format.html { redirect_to user_events_url, notice: 'User event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_event
      @user_event = UserEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_event_params
      params.require(:user_event).permit(:user_id, :event_id, :participant_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sources_helper.rb
module SourcesHelper
end

app/helpers/user_events_helper.rb
module UserEventsHelper
end

app/views/user_events/_form.html.erb
<%= form_with(model: user_event, local: true) do |form| %>
  <% if user_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_event.errors.count, "error") %> prohibited this user_event from being saved:</h2>

      <ul>
      <% user_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :user_event_user_id %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id, id: :user_event_event_id %>
  </div>

  <div class="field">
    <%= form.label :participant_type %>
    <%= form.text_field :participant_type, id: :user_event_participant_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_events/edit.html.erb
<h1>Editing User Event</h1>

<%= render 'form', user_event: @user_event %>

<%= link_to 'Show', @user_event %> |
<%= link_to 'Back', user_events_path %>

app/views/user_events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Events</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th>Participant type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_events.each do |user_event| %>
      <tr>
        <td><%= user_event.user %></td>
        <td><%= user_event.event %></td>
        <td><%= user_event.participant_type %></td>
        <td><%= link_to 'Show', user_event %></td>
        <td><%= link_to 'Edit', edit_user_event_path(user_event) %></td>
        <td><%= link_to 'Destroy', user_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Event', new_user_event_path %>

app/views/user_events/new.html.erb
<h1>New User Event</h1>

<%= render 'form', user_event: @user_event %>

<%= link_to 'Back', user_events_path %>

app/views/user_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_event.user %>
</p>

<p>
  <strong>Event:</strong>
  <%= @user_event.event %>
</p>

<p>
  <strong>Participant type:</strong>
  <%= @user_event.participant_type %>
</p>

<%= link_to 'Edit', edit_user_event_path(@user_event) %> |
<%= link_to 'Back', user_events_path %>